### ISSUE TITLE
Can I export NFive plugin function(s) to other plugin?

### ISSUE THREAD

**Issue by zndn1997** [NFive/NFive#37]
Event is only way?

**Comment by JoeBiellik** [comment]
NFive is designed to be pretty much self contained, we can't provide support for other resources.

The NFive communications APIs do a number of things which make the events incompatible with traditional FiveM events, however you [can just drop down to FiveM events and exports](https://github.com/NFive/SDK.Client/blob/master/Services/Service.cs#L25-L26) for interop if need be.

**Comment by steveski** [comment]
What about simple resources that just have a stream folder with ytds?

**Comment by IgiCodes** [comment]
> What about simple resources that just have a stream folder with ytds?

Not sure what you mean here.
This issue is about interop between NFive plugins and non-NFive resources.
A resource that just streams assets is completely irrelevant to a framework and works with separate to NFive.

**Comment by IgiCodes** [comment]
Also closing this issue as it was answered nearly a year ago now, please open a new issue with a more accurate question if still needed.
